name: Run all tests

on: [push]

jobs:
  build:
    # Job name is Greeting
    name: ${{ matrix.test_script }} (${{ matrix.os }})
    # This job runs on Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-16.04]
        test_script: ['test_rules_scala', 'test_reproducibility', 'test_version']
        include:
          - os: ubuntu-16.04
            test_script: 'test_lint'
          - os: ubuntu-16.04
            test_script: 'test_examples'
          - os: ubuntu-16.04
            test_script: 'test_rules_scala_with_latest_bazel'
            experimental: true
          
    steps:
      - name: install bazelisk
        run: |
            SYS_ENV_PLATFORM=linux
            if uname -a | grep Darwin; then
              SYS_ENV_PLATFORM=darwin
            else
              sudo apt install -y libxml2-utils
            fi
            sudo curl -L --output /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-${SYS_ENV_PLATFORM}-amd64
            sudo chmod +x /usr/local/bin/bazel

      - uses: actions/checkout@v2

      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: .bazel_cache
          key: ${{ runner.os }}-${{ matrix.test_script }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.test_script }}--${{ github.ref }}
            ${{ runner.os }}-${{ matrix.test_script }}--refs/heads/master

      - name: ${{ matrix.test_script }}
        env: 
          DEVELOPER_DIR: '/Applications/Xcode_10.1.app/Contents/Developer'
        run: |
            cat .bazelrc.travis >> .bazelrc
            bash ./${{ matrix.test_script }}.sh ci
